pristavkin/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

pristavkin/checkout/urls.py
from django.urls import path

from .views import checkout, create_order, thank_you

app_name = 'checkout'

urlpatterns = [
    path('', checkout, name='checkout'),
    path('create-order/', create_order, name='create_order'),
    path('thank-you/<int:order_id>/', thank_you, name='thank_you'),
]

pristavkin/pristavkin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('checkout/', include('checkout.urls')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

pristavkin/shop/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', views.product_list, name='product_list'),
    path('<category_slug>',
         views.product_list,
         name='product_list_by_category'),
    path('<slug>/',
         views.product_detail,
         name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pristavkin/users/urls.py
from . import views

from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, LogoutView
from .views import *
from django.contrib import admin
from django.urls import path, include
app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('auth/signup/', SignUp.as_view(), name='signup'),
    path(
        'auth/login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'auth/logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/managment/password_reset_form.html',
            email_template_name='users/managment/password_reset_email.html',
            success_url='done/'),
        name='password_reset_form'
    ),

    path('auth/password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/managment/password_reset_done.html'),
         name='password_reset_done'),

    path('auth/reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/managment/reset_done.html'),
         name='reset_done'),

    path('auth/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/managment/password_reset_confirm.html',
             success_url=reverse_lazy('users:reset_done')),
         name='password_reset_confirm'),

    path(
        'auth/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/managment/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/managment/password_change_form.html',
            success_url='done/'),
        name='password_change'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/managment/password_change_done.html'),
        name='password_change_done'
    ),
]

pristavkin/checkout/models.py
from django.contrib.auth.models import User
from django.db import models

from shop.models import Product


class Order(models.Model):
    PAYMENT_METHOD_CHOICES = [
        ('cash_courier', 'Наличными курьеру'),
        ('card_courier', 'Картой курьеру'),
        ('card_online', 'Картой онлайн'),
    ]
    STATUS_CHOICES = [
        ('created', 'Создан'),
        ('processing', 'Обрабатывается'),
        ('shipped', 'Отправлен'),
        ('delivered', 'Доставлен'),
        ('canceled', 'Отменен'),
    ]
    payment_method = models.CharField(
        max_length=20,
        choices=PAYMENT_METHOD_CHOICES,
        verbose_name='Способ оплаты',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='orders',
        verbose_name='Покупатель',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания',
    )
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default='created',
        verbose_name='Статус',
    )

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'
        ordering = ['-created_at']

    @property
    def total_price(self):
        total_price = sum(
            order_item.total_price for order_item in self.items.all())
        return total_price

    def __str__(self):
        return f"Заказ номер {self.id} для {self.user}"


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='items',
        verbose_name='Заказ',
    )
    item = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Товар',)
    quantity = models.PositiveIntegerField(
        default=1, verbose_name='Количество',)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Цена',)

    class Meta:
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    @property
    def total_price(self):
        total_price = self.quantity * self.item.price
        return total_price

    def __str__(self):
        return f"{self.quantity} x {self.item.name} in Order {self.order.id}"


class ShippingAddress(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя',)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия',)
    email = models.EmailField(verbose_name='Почта',)
    phone = models.CharField(max_length=20, verbose_name='Телефон',)
    address_line_1 = models.CharField(max_length=200, verbose_name='Адрес',)
    address_line_2 = models.CharField(max_length=200, blank=True, null=True, verbose_name='Адрес (дополнительно)',)
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='shipping_address', verbose_name='Заказ',)

    class Meta:
        verbose_name = 'Адрес доставки'
        verbose_name_plural = 'Адреса доставки'

    def __str__(self):
        return f"""
        {self.address_line_1} {self.address_line_2}
        Для: {self.first_name} {self.last_name},
        Почта: {self.email},
        Телефон: {self.phone}
        """

pristavkin/checkout/forms.py
from django import forms

from .models import Order


class PlaceholderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(PlaceholderForm, self).__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.widget.attrs['placeholder'] = field.help_text


class OrderCreateForm(PlaceholderForm):
    first_name = forms.CharField(max_length=100, help_text='Имя')
    last_name = forms.CharField(max_length=100, help_text='Фамилия')
    email = forms.EmailField(help_text='Email')
    phone = forms.CharField(max_length=20, help_text='Телефон')
    address_line_1 = forms.CharField(max_length=100, help_text='Адрес')
    address_line_2 = forms.CharField(
        max_length=100,
        required=False,
        help_text='Адрес (дополнительно)'
    )
    payment_method = forms.ChoiceField(choices=Order.PAYMENT_METHOD_CHOICES)

pristavkin/checkout/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from cart.views import Cart
from .forms import OrderCreateForm
from .models import Order, OrderItem, ShippingAddress


@login_required
def checkout(request):
    """
    Представление чекаута.
    """
    cart = Cart.objects.get(user=request.user)
    form = OrderCreateForm()
    context = {'cart': cart, 'form': form}

    return render(request, 'checkout/checkout.html', context)


@login_required
def thank_you(request, order_id):
    """
    Страница благодарности за заказ.
    """
    order = get_object_or_404(Order, id=order_id, user=request.user)
    return render(request, 'checkout/thank_you.html', {'order': order})


@login_required
def create_order(request):
    """
    Создание экземпляров Order и ShippingAddress
    из формы и редирект в профиль пользователя,
    либо передаем форму обратно.
    """
    cart = get_object_or_404(Cart, user=request.user)

    if cart.items.exists() and request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = Order.objects.create(
                payment_method=form.cleaned_data['payment_method'],
                user=request.user,
            )

            ShippingAddress.objects.create(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
                phone=form.cleaned_data['phone'],
                address_line_1=form.cleaned_data['address_line_1'],
                address_line_2=form.cleaned_data['address_line_2'],
                order=order,
            )

            for cart_item in cart.items.all():
                OrderItem.objects.create(
                    order=order,
                    item=cart_item.item,
                    quantity=cart_item.quantity,
                    price=cart_item.item.price
                )

            cart.clear()
            return redirect('checkout:thank_you', order_id=order.id)
    else:
        form = OrderCreateForm()
    messages.warning(
        request, 'Форма не была корректно обработана, введите данные еще раз')
    context = {'form': form, 'cart': cart}
    return render(request, 'checkout/checkout.html', context)

pristavkin/templates/checkout/checkout.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>Pristavkin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{static 'img/apple-icon.png"}>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}">
    <link rel="stylesheet" href="{% static "css/templatemo.css"%}">
    <link rel="stylesheet" href="{% static "css/custom.css"%}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css'%}">
<!--


-->
</head>
{% csrf_token %}
<body>
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">matveyvlasov364@gmail.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">+7(909)-570-00-32</a>
                </div>
                <div>
                    <a class="text-light" href="https://www.instagram.com/zxcdubina?igsh=MXBhZHA2bTkxYTN5MA%3D%3D&utm_source=qr" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->


    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'shop:product_list' %}">
                Pristavkin
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Магазин</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Контакты</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'cart:cart' %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>

                    </a>
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:profile' %}">
                        <i class="fa fa-fw fa-user text-dark mr-3"></i>

                    </a>
                </div>
            </div>

        </div>
    </nav>
    <!-- Close Header -->

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>



    <!-- Start Content -->
    <style>


   .prof-container {
    width: 80%;
    max-width: 800px;
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,0.3);
    margin: 50px auto;
    width: 50%;
    border: 1px solid #ccc;
    padding: 20px;
    border-radius: 10px;
    text-align: center;
   }

   .prof-container img {
    width: 30%;
    height: 30%;

   }

   h1 {
    text-align: center;
    font-size: 36px;
    margin-bottom: 20px;
   }

   p {
    font-size: 18px;
    line-height: 1.5;
    margin-bottom: 10px;
   }

    .prof-container button{
        background-color: #000000;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
 </style>

 <div class="prof-container">



{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "css/checkout.css"%}" />
{% endblock %}

{% block content %}
<h1>Оформление заказа</h1>
{% if messages %}
<div class="messages-container">
  <ul class="messages">
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
  </ul>
</div>
{% endif %}
<form method="post" action="{% url 'checkout:create_order'%}">
  {% csrf_token %}
  <section>
  <div class="row">
    <div class="col-md-8" style="width: 60%; padding-right: 20px;">
      <div><h2>Доставка</h2></div>
      {% for field in form %}
        {% if field.name != 'payment_method' %}
          <div class="form-group">
            {{ field }}
            <div class="text-danger error-message">
              {% for error in field.errors %}
                <span>{{ error }}</span>
              {% endfor %}
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-md-4" style="width: 40%;">
      <h2>Ваш заказ</h2>
      {% if cart.items.exists %}
        <div class="table-wrapper">
          <table class="alt">
            <thead>
              <tr>
                <th>Название</th>
                <th>Количество</th>
                <th>Цена</th>
              </tr>
            </thead>
            <tbody>
              {% for cart_item in cart.items.all %}
              <tr>
                <td>{{ cart_item.item.name|truncatechars:20 }}</td>
                <td>
                    {{ cart_item.quantity }}
                </td>
                <td>{{ cart_item.total_price }}</td>
              </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <td colspan="2"></td>
                <td><b>{{ cart.total_price }}</b></td>
              </tr>
            </tfoot>
          </table>
        </div>
      {% else %}
        Корзина пустая
        <a href="{% url 'store:home' %}"  style="margin-bottom: 100px; margin-top: 50px;" class="button">Вернуться на главную</a>
      {% endif %}
      <div><h2>Выберите способ оплаты</h2></div>
      {{ form.payment_method }}
      <!-- Всплывающее окно для опции "Картой онлайн" -->
      {% include 'checkout/popup.html' %}
    </div>
  </section>
    <div class="actions" style="text-align: justify; margin-top: 100px;">
      <input type="reset" value="Сбросить" style="float: left;">
      {% if cart.items.exists %}
        <input type="submit" value="Оставить заказ" class="primary" style="float: right;">
      {% else %}
        <input type="submit" value="Оставить заказ" class="primary disabled" style="float: right;">
      {% endif %}
    </div>
  </div>
</form>
{% endblock %}

{% block js %}
<script src={% static "js/checkout.js"%}></script>
<!-- PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src={% static "js/payment.js"%}></script>
{% endblock %}

 </div>
    <!-- End Content -->

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Наши Бренды</h1>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a><img class="img-fluid brand-img"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{% static 'img/Sony-PlayStation-Transparent-Images-PNG.png'%}" alt="Brand Logo"></a>
                                            </div>

                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{%static 'img/Xbox_logo_(2019).svg.png'%}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a><img class="img-fluid brand-img"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End First slide-->
                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->


    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Pristavkin</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            Санкт-Петербург
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">+7(909)-570-00-32</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">matveyvlasov364@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                </div>

                <div class="col-md-4 pt-5">

                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/zxcdubina?igsh=MXBhZHA2bTkxYTN5MA%3D%3D&utm_source=qr"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="w-100 py-3">
        </div>


    </footer>
    <!-- End Footer -->

   <!-- Start Script -->
    <script src="{%static 'js/jquery-1.11.0.min.js'%}"></script>
    <script src="{%static 'js/jquery-migrate-1.2.1.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{%static 'js/templatemo.js'%}"></script>
    <script src="{%static 'js/custom.js'%}"></script>
    <!-- End Script -->
</body>

</html>

pristavkin/templates/checkout/popup.html
<div id="overlay" class="overlay"></div>
<div id="online-payment-info" class="hidden">
  <button id="close-btn">Закрыть</button>

  <div id="paypal-button-container"></div>

</div>