pristavkin/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

pristavkin/pristavkin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('user/', include(('users.urls', 'users'), namespace='users')),
    path('checkout/', include('checkout.urls')),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
]

pristavkin/shop/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(r'', views.product_list, name='product_list'),
    path('<category_slug>',
         views.product_list,
         name='product_list_by_category'),
    path('<slug>/',
         views.product_detail,
         name='product_detail'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

pristavkin/users/urls.py
from . import views

from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, \
    PasswordResetConfirmView, PasswordChangeView, PasswordChangeDoneView, LogoutView
from .views import *
from django.contrib import admin
from django.urls import path, include
app_name = 'users'

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('auth/signup/', SignUp.as_view(), name='signup'),
    path(
        'auth/login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'auth/logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/managment/password_reset_form.html',
            email_template_name='users/managment/password_reset_email.html',
            success_url='done/'),
        name='password_reset_form'
    ),

    path('auth/password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/managment/password_reset_done.html'),
         name='password_reset_done'),

    path('auth/reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/managment/reset_done.html'),
         name='reset_done'),

    path('auth/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/managment/password_reset_confirm.html',
             success_url=reverse_lazy('users:reset_done')),
         name='password_reset_confirm'),

    path(
        'auth/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/managment/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/managment/password_change_form.html',
            success_url='done/'),
        name='password_change'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/managment/password_change_done.html'),
        name='password_change_done'
    ),
]

pristavkin/users/models.py
from django.db import models

# Create your models here.

pristavkin/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
User = get_user_model()




class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

pristavkin/users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .forms import CreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


# Create your views here.


class SignUp(CreateView):
    form_class = CreationForm

    success_url = reverse_lazy('shop:home')
    template_name = 'users/signup.html'




@login_required
def profile(request):
    """
    Представление профиля пользователя.
    """
    return render(request, 'users/profile.html')

pristavkin/templates/users/logged_out.html
{% block content %}
  <h1>Вы успешно вышли из системы</h1>
  <p>Вернуться на <a href="{% url 'users:login' %}">страницу входа</a>.</p>
{% endblock %}

pristavkin/templates/users/login.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/style.css'%}">
  <script src="{% static 'js/auth.js'%}"></script>
</head>
{% csrf_token %}
<div class="login-page">
  <div class="form">
    {% for field in form %}
    <form class="login-form" method="post" >
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
      {% if form.errors %}
        <div class="alert alert-danger">
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
                <span class="error-message">{{ error }}</span>
            {% endfor %}
          {% endfor %}
  </div>
{% endif %}
{% endfor %}
      <button type="submit">Войти</button>


      <p class="message">Not registered? <a href="{% url 'users:signup' %}">Create an account</a></p>
    </form>
  </div>

pristavkin/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <title>Pristavkin</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="{static 'img/apple-icon.png"}>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico'%}">

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css"%}">
    <link rel="stylesheet" href="{% static "css/templatemo.css"%}">
    <link rel="stylesheet" href="{% static "css/custom.css"%}">

    <!-- Load fonts style after rendering the layout styles -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">
    <link rel="stylesheet" href="{% static 'css/fontawesome.min.css'%}">
<!--


-->
</head>
{% csrf_token %}
<body>
    <!-- Start Top Nav -->
    <nav class="navbar navbar-expand-lg bg-dark navbar-light d-none d-lg-block" id="templatemo_nav_top">
        <div class="container text-light">
            <div class="w-100 d-flex justify-content-between">
                <div>
                    <i class="fa fa-envelope mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="mailto:info@company.com">matveyvlasov364@gmail.com</a>
                    <i class="fa fa-phone mx-2"></i>
                    <a class="navbar-sm-brand text-light text-decoration-none" href="tel:010-020-0340">+7(909)-570-00-32</a>
                </div>
                <div>
                    <a class="text-light" href="https://www.instagram.com/zxcdubina?igsh=MXBhZHA2bTkxYTN5MA%3D%3D&utm_source=qr" target="_blank"><i class="fab fa-instagram fa-sm fa-fw me-2"></i></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- Close Top Nav -->


    <!-- Header -->
    <nav class="navbar navbar-expand-lg navbar-light shadow">
        <div class="container d-flex justify-content-between align-items-center">

            <a class="navbar-brand text-success logo h1 align-self-center" href="{% url 'shop:product_list' %}">
                Pristavkin
            </a>

            <button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#templatemo_main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between" id="templatemo_main_nav">
                <div class="flex-fill">
                    <ul class="nav navbar-nav d-flex justify-content-between mx-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Магазин</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Контакты</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar align-self-center d-flex">
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'cart:cart' %}">
                        <i class="fa fa-fw fa-cart-arrow-down text-dark mr-1"></i>

                    </a>
                    <a class="nav-icon position-relative text-decoration-none" href="{% url 'users:profile' %}">
                        <i class="fa fa-fw fa-user text-dark mr-3"></i>

                    </a>
                </div>
            </div>

        </div>
    </nav>

    <!-- Modal -->
    <div class="modal fade bg-white" id="templatemo_search" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="w-100 pt-1 mb-5 text-right">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="" method="get" class="modal-content modal-body border-0 p-0">
                <div class="input-group mb-2">
                    <input type="text" class="form-control" id="inputModalSearch" name="q" placeholder="Search ...">
                    <button type="submit" class="input-group-text bg-success text-light">
                        <i class="fa fa-fw fa-search text-white"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>



    <!-- Start Content -->
    <style>


   .prof-container {
    width: 80%;
    max-width: 800px;
    background-color: #fff;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 0 10px rgba(0,0,0,0.3);
    margin: 50px auto;
    width: 50%;
    border: 1px solid #ccc;
    padding: 20px;
    border-radius: 10px;
    text-align: center;
   }

   .prof-container img {
    width: 30%;
    height: 30%;

   }

   h1 {
    text-align: center;
    font-size: 36px;
    margin-bottom: 20px;
   }

   p {
    font-size: 18px;
    line-height: 1.5;
    margin-bottom: 10px;
   }

    .prof-container button{
        background-color: #000000;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
 </style>

 <div class="prof-container">
  <h1>Страница пользователя</h1>
  <img src="{% static 'img/profile.png'%}" alt="ava">
  </br>
  <p>Имя: {{ user.name }}</p>
  <p>Почта: {{ user.email }}</p>
  <br>
  <a href="{% url 'users:logout' %}">
   <button>Выйти из аккаунта</button>
  </a>


 </div>
    <!-- End Content -->

    <!-- Start Brands -->
    <section class="bg-light py-5">
        <div class="container my-4">
            <div class="row text-center py-3">
                <div class="col-lg-6 m-auto">
                    <h1 class="h1">Наши Бренды</h1>
                </div>
                <div class="col-lg-9 m-auto tempaltemo-carousel">
                    <div class="row d-flex flex-row">
                        <!--Controls-->
                        <!--End Controls-->

                        <!--Carousel Wrapper-->
                        <div class="col">
                            <div class="carousel slide carousel-multi-item pt-2 pt-md-0" id="multi-item-example" data-bs-ride="carousel">
                                <!--Slides-->
                                <div class="carousel-inner product-links-wap" role="listbox">

                                    <!--First slide-->
                                    <div class="carousel-item active">
                                        <div class="row">
                                            <div class="col-3 p-md-5">
                                                <a><img class="img-fluid brand-img"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{% static 'img/Sony-PlayStation-Transparent-Images-PNG.png'%}" alt="Brand Logo"></a>
                                            </div>

                                            <div class="col-3 p-md-5">
                                                <a href="#"><img class="img-fluid brand-img" src="{%static 'img/Xbox_logo_(2019).svg.png'%}" alt="Brand Logo"></a>
                                            </div>
                                            <div class="col-3 p-md-5">
                                                <a><img class="img-fluid brand-img"></a>
                                            </div>
                                        </div>
                                    </div>
                                    <!--End First slide-->
                                </div>
                                <!--End Slides-->
                            </div>
                        </div>
                        <!--End Carousel Wrapper-->

                        <!--Controls-->
                        <!--End Controls-->
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End Brands-->


    <!-- Start Footer -->
    <footer class="bg-dark" id="tempaltemo_footer">
        <div class="container">
            <div class="row">

                <div class="col-md-4 pt-5">
                    <h2 class="h2 text-success border-bottom pb-3 border-light logo">Pristavkin</h2>
                    <ul class="list-unstyled text-light footer-link-list">
                        <li>
                            <i class="fas fa-map-marker-alt fa-fw"></i>
                            Санкт-Петербург
                        </li>
                        <li>
                            <i class="fa fa-phone fa-fw"></i>
                            <a class="text-decoration-none" href="tel:010-020-0340">+7(909)-570-00-32</a>
                        </li>
                        <li>
                            <i class="fa fa-envelope fa-fw"></i>
                            <a class="text-decoration-none" href="mailto:info@company.com">matveyvlasov364@gmail.com</a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-4 pt-5">
                </div>

                <div class="col-md-4 pt-5">

                </div>

            </div>

            <div class="row text-light mb-4">
                <div class="col-12 mb-3">
                    <div class="w-100 my-3 border-top border-light"></div>
                </div>
                <div class="col-auto me-auto">
                    <ul class="list-inline text-left footer-icons">
                        <li class="list-inline-item border border-light rounded-circle text-center">
                            <a class="text-light text-decoration-none" target="_blank" href="https://www.instagram.com/zxcdubina?igsh=MXBhZHA2bTkxYTN5MA%3D%3D&utm_source=qr"><i class="fab fa-instagram fa-lg fa-fw"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="w-100 py-3">
        </div>


    </footer>
    <!-- End Footer -->

   <!-- Start Script -->
    <script src="{%static 'js/jquery-1.11.0.min.js'%}"></script>
    <script src="{%static 'js/jquery-migrate-1.2.1.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.bundle.min.js'%}"></script>
    <script src="{%static 'js/templatemo.js'%}"></script>
    <script src="{%static 'js/custom.js'%}"></script>
    <!-- End Script -->
</body>

</html>

pristavkin/templates/users/signup.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/style.css'%}" />
</head>
{% csrf_token %}
<div class="login-page">
  <div class="form">
    {% for field in form %}
    <form class="login-form" method="post" action="{% url 'users:signup' %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
        {% if form.errors %}
        <div class="alert alert-danger">
          {% for error in field.errors %}
            <p>{{ error }}</p>
          {% endfor %}
      </div>
  {% endif %}
  {% endfor %}
      <button type="submit" class="btn btn-primary">
    Зарегистрироваться
  </button>
      <p class="message">Уже есть аккаунт? <a href="{% url 'users:login' %}">Войти</a></p>
    </form>
  </div>
</div>